general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:
    sequences:
      priority_level_1: [sq_auto_anc_anc_barrel, sq_auto_anc_anc_slalom, sq_auto_anc_anc_bounce, sq_pure_pursuit_test, sq_auto_gscr_a_blue, sq_auto_gscr_a_red, sq_auto_gscr_b_blue, sq_auto_gscr_b_red,
                         sq_auto_gsc_a_blue, sq_auto_gsc_a_red, sq_auto_gsc_b_blue, sq_auto_gsc_b_red ]
    parallels:
      priority_level_2: [ pl_shoot ]
      priority_level_1: [ pl_prime_to_shoot ]
    ss_drivetrain:
      priority_level_3: [ st_drivetrain_zero ]
      priority_level_2: [ st_drivetrain_pure_pursuit_test, st_drivetrain_swerve_align_test ]
      priority_level_1: [ st_drivetrain_swerve, st_drivetrain_swerve_math, st_drivetrain_gscr_a_blue, st_drivetrain_gscr_a_red, st_drivetrain_gscr_b_blue, st_drivetrain_gscr_b_red,
                          st_drivetrain_gsc_a_blue, st_drivetrain_gsc_a_red, st_drivetrain_gsc_b_blue, st_drivetrain_gsc_b_red, st_drivetrain_anc_barrel, st_drivetrain_anc_slalom, st_drivetrain_anc_bounce ]
      default: [  ]
    ss_collector:
      priority_level_1: [ st_collector_collect, st_collector_eject, st_collector_stop]
    ss_elevator:
      priority_level_1: [ st_elevator_shoot, st_elevator_eject, st_elevator_stop ]
    ss_flywheel:
      priority_level_1: [ st_flywheel_zero, st_flywheel_shoot, st_flywheel_prime ]
      default: [ st_flywheel_stop ]

  subsystems: [ ss_drivetrain, ss_collector, ss_elevator, ss_flywheel ]

  input_booleans: [ ipb_driver_back, ipb_driver_start, ipb_driver_left_trigger, ipb_driver_a, ipb_driver_x, ipb_driver_y, ipb_driver_right_bumper, ipb_driver_right_trigger, ipb_driver_dpad_up, ipb_driver_dpad_down ]

  input_numerics: [ ipn_driver_left_y, ipn_driver_left_x, ipn_driver_right_y, ipn_driver_right_x ]

  input_vectors: [ ipv_navx,
                   ipv_limelight_shooter,
                   ipv_drivetrain_front_right_angle, ipv_drivetrain_front_left_angle, ipv_drivetrain_back_left_angle, ipv_drivetrain_back_right_angle,
                   ipv_swerve_odometry ]

  output_numerics: [ opn_drivetrain_front_right_speed, opn_drivetrain_front_left_speed, opn_drivetrain_back_left_speed, opn_drivetrain_back_right_speed,
                     opn_drivetrain_front_right_angle, opn_drivetrain_front_left_angle, opn_drivetrain_back_left_angle, opn_drivetrain_back_right_angle,
                     opn_collector, opn_elevator, opn_flywheel ]

  output_booleans: [ ]

global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain_swerve_math:
  x_left_js: ipn_driver_left_x
  y_left_js: ipn_driver_left_y
  x_right_js: ipn_driver_right_x
  y_right_js: ipn_driver_right_y
  robot_length: 18.5
  robot_width: 16.5
  navx: ipv_navx

global_drivetrain_swerve:
  max_module_velocity: 170.0
  module_positions: [ [ 9.25, -8.25 ], [ 9.25, 8.25 ], [ -9.25, 8.25 ], [ -9.25, -8.25 ] ]
  input_angle_names: [ ipv_drivetrain_front_right_angle, ipv_drivetrain_front_left_angle, ipv_drivetrain_back_left_angle, ipv_drivetrain_back_right_angle ]
  input_position_names: [ ipn_drivetrain_front_right_angle_position, ipn_drivetrain_front_left_angle_position, ipn_drivetrain_back_left_angle_position, ipn_drivetrain_back_left_angle_position]
  output_angle_names: [ opn_drivetrain_front_right_angle, opn_drivetrain_front_left_angle, opn_drivetrain_back_left_angle, opn_drivetrain_back_right_angle ]
  output_speed_names: [ opn_drivetrain_front_right_speed, opn_drivetrain_front_left_speed, opn_drivetrain_back_left_speed, opn_drivetrain_back_right_speed ]
  navx: ipv_navx
  limelight: ipv_limelight_shooter
  odometry: ipv_swerve_odometry
  heading_controller: pr_swerve_heading
  swerve_x: ipn_driver_left_x
  swerve_y: ipn_driver_left_y
  swerve_rotate: ipn_driver_right_x
  swerve_field_oriented_button: ipb_driver_start
  slow_mode_button: ipb_driver_left_trigger
  scale_factor: 0.1


global_flywheel:
  #original was ipb_driver_x but now it's bad
  adjust_flywheel_speed_button: ipb_driver_right_trigger
  adjust_up_button: ipb_driver_dpad_up
  adjust_down_button: ipb_driver_dpad_down
  increment: 1.0
  speed_profile:
    10.0: 6250
    15.0: 5150
    18.0: 5100
    24.0: 6000

global_limelight:
  limelight: ipv_limelight_shooter

log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: [gsc, gscr, anc]
    destinations: [a, b, anc, ball]
    actions: [blue, red, barrel, slalom, bounce, pattern]

  match_values:

